package recommender.text;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Hashtable;
import java.util.Iterator;
import java.util.List;

import org.apache.lucene.analysis.Analyzer;
import org.apache.lucene.analysis.standard.StandardAnalyzer;
import org.apache.lucene.document.Document;
import org.apache.lucene.index.DirectoryReader;
import org.apache.lucene.queryparser.classic.ParseException;
import org.apache.lucene.queryparser.classic.QueryParser;
import org.apache.lucene.search.IndexSearcher;
import org.apache.lucene.search.Query;
import org.apache.lucene.search.ScoreDoc;

import recommender.utils.RecommendersInformation;
import utils.IndexFields;
import utils.TextUtils;
import entity.Prediction;

public class TextRecommender {

	private IndexSearcher searcher;
	private long recommendationTime;
	private int recommendationCount;
	private long trainingTime;
	private double precision;
	private double recall;

	public TextRecommender(RecommendersInformation recommendersInformation) {
		try {
			DirectoryReader reader = DirectoryReader.open(recommendersInformation.getLuceneDirectory());
			searcher = new IndexSearcher(reader);
		} catch (IOException e) {
			System.err.println(e.getMessage());
		}
	}

	public List<Prediction> recommendItems(String text) {
		List<Prediction> result = new ArrayList<Prediction>();
		long ini = System.currentTimeMillis();
		if(text != null && !text.isEmpty()){
			text = TextUtils.cleanText(text);
			try {
				Analyzer analyzer = new StandardAnalyzer();
				QueryParser parser = new QueryParser(IndexFields.TEXT, analyzer);
				Query query = parser.parse(text);
				ScoreDoc[] docs = searcher.search(query, 20).scoreDocs;
				float min = Float.MAX_VALUE;
				float max = 0;
				
				for (ScoreDoc d : docs) {
					min = Math.min(min, d.score);
					max = Math.max(max, d.score);
				}
				
				for (ScoreDoc d : docs) {
					Document hitDoc = searcher.doc(d.doc);
					String businessId = hitDoc.get(IndexFields.BUSINESS_ID);
					double value = estimatePreference(d, min, max);
					result.add(new Prediction(businessId, value));
				}
			} catch (IOException e) {
			} catch (ParseException e) {
			}
		}
		recommendationCount++;
		recommendationTime += (System.currentTimeMillis()) - ini;
		return result;
	}

	public double estimatePreference(ScoreDoc d, float min, float max) {
		double value = ((d.score - min) * 5) / (max - min);
		return value;
	}

	public void init() throws Exception {
		precision = 0.0D;
		recall = 0.0D;
		Hashtable<String, HashSet<String>> test = new Hashtable<String, HashSet<String>>();
		HashSet<String> relevant = new HashSet<String>();
		relevant.add("vcNAWiLM4dR7D2nwwJ7nCA");
		test.put("Goldberg", relevant);
		test.put("Good bar food", getGoodBarFood());
		test.put("cheap beer", getCheapBeer());
		test.put("best french toast ever", getFrenchToast());
		test.put("Best breakfast", getBestBreakFast());
		test.put("The food was fine", getFoodFine());
		
		long ini = System.currentTimeMillis();
		Analyzer analyzer = new StandardAnalyzer();
		QueryParser parser = new QueryParser(IndexFields.TEXT, analyzer);
		Iterator<String> it = test.keySet().iterator();
		while(it.hasNext()){
			int tp = 0;
			String q = it.next();
			relevant = test.get(q);
			Query query = parser.parse(q);
			ScoreDoc[] docs = searcher.search(query, 10).scoreDocs;
			for (ScoreDoc d : docs) {
				Document hitDoc = searcher.doc(d.doc);
				String businessId = hitDoc.get(IndexFields.BUSINESS_ID);
				if (relevant.contains(businessId)) {
					tp++;
				}
			}
			precision += (double) tp / (double) docs.length;
			recall += (double) tp / (double) relevant.size();
		}
		
		precision = precision / 6.0;
		recall = recall / 6.0;
		
		trainingTime = System.currentTimeMillis() - ini;
	}

	private HashSet<String> getFoodFine() {
		HashSet<String> hs = new HashSet<String>();
		hs.add("6p9TlP2I8S4agxYMNFSDjg");
		hs.add("FiXamVMgMf9U0VqFHDZSEA");
		hs.add("KjymOs12Mpy0Kd54b7T9MA");
		hs.add("n_QAA70NrnGIsGjog3HF_Q");
		hs.add("oQnEBD0vu7XjJpofArA5aw");
		hs.add("rBPQuQgTcMtUq5-RYhY2uQ");
		hs.add("4uGHPY-OpJN08CabtTAvNg");
		hs.add("YPoHtUq85TmNrBpqj_zmuA");
		hs.add("Dz7swOgFook-L89Y_M-aQA");
		hs.add("gGeVLZ9j_wAYKbaqgnKSJA");
		hs.add("8zL3V6rmFKBess3bxPLAoQ");
		hs.add("ilJiRYZgxjrEu2iexKu-pQ");
		hs.add("mhLN_oiJd7zq6eaOS1Nw1A");
		hs.add("rNahhyqDlouyDMHh57p3ug");
		hs.add("vYEUEID47mgenrTBsvL9Xw");
		hs.add("URweBWkD1EgPDFUlL0LOKQ");
		hs.add("Sx5wIQReufLKwlb-cSQ8JQ");
		hs.add("6VRbbNQe5ouWmwsMebUMkg");
		hs.add("M1n4HVSdD9FIyfmIoxxRrg");
		hs.add("Y1sSdaeuicOzR87DIREinw");
		hs.add("XNSito__Fne14TXU0vz1Qw");
		hs.add("xEg0-xrQywU5K-WQO7cy0w");
		hs.add("JsDZZ9S3qntzCfo5N_Ci6A");
		hs.add("s26P-jeVUH9TjnTPQttPag");
		hs.add("gIRXVrjGxX1ImsS0an8anA");
		hs.add("js12Ev8XKlh36gZeGHzQnA");
		hs.add("0wO_vZKvKGd6JFAnV7h3-Q");
		hs.add("VHbCWYwD_xw1TWkgdQRqIw");
		hs.add("qlrZzAktK8wODSHxhLEK7w");
		hs.add("jsENu6YLygHA5Z-Vc7Ku2A");
		hs.add("VzG3VWLnGCrRaQGgtcmtow");
		hs.add("6VpBO3WUToqfFQYEXnmD2A");
		hs.add("88mPrywH1ox-7ILDB0e2hw");
		hs.add("Bqs7_QlIF5hHt7_HyZYO8w");
		hs.add("pwpl-rxwNRQdgqFz_-qMPg");
		hs.add("9CcqBiB89ExGHr9WV7a1mg");
		hs.add("d6CUe9LjkFFqYtt7WuW5Lg");
		hs.add("WBxuIQsxGl7vNe5MXYszCA");
		hs.add("g2On1JEPKrLm13Cwcr5MjA");
		hs.add("UrIT2RgnCg3OfRBr9J3h7w");
		hs.add("Te5dA0G1-SWKGS8nuJp0Tg");
		hs.add("gMVWJi_dldZfofI7EShmNA");
		hs.add("6IRoWd6N__OVMNQfvu1Ccw");
		hs.add("zSzE4rW9FE3fGqiEzZ91Vw");
		hs.add("4PatE4TUcea0Dj0hKICGJw");
		hs.add("F1UsF9LU5h7xp1k9LytT-w");
		hs.add("kyPTfVzZfopYwZyZ4hhLMw");
		hs.add("cN6qpVw6RaSrSI-JGGF4Tw");
		hs.add("SLIsUQDQ8vCmGlUFtuTVxA");
		hs.add("bzQPFOLLxuwx7K7dw8j7Zw");
		hs.add("APxVYJuGqlUqr4ncoY5uLg");
		hs.add("2KiC2dj6rf3UWuvj6RPAgw");
		hs.add("48Qg18SR0flit8fAvHAcvQ");
		hs.add("2y-zifC8_V5XUTsyCSWvdQ");
		hs.add("BPi1Q5wX0_o5VlO_XRyYuQ");
		hs.add("v7OwbHgNgy_VQ9eP5FjvUA");
		hs.add("jgHNa2VHgeCANh8bgFDjjQ");
		hs.add("hsM6PF4Of6RMNcQV_c-FVQ");
		hs.add("s0aRh5eiJIPV4iDRRSR8Ew");
		hs.add("Fvzifot1f27zM-Z6gsNHmg");
		hs.add("wehqTDVRZsOkESgAoYBhow");
		hs.add("oIXw9z-OuDlMDKUBPRny2w");
		hs.add("Viqmo4OgTd15DWWDNQ0pDQ");
		hs.add("JId49VgiWOS30qK7tn3JXw");
		hs.add("YeKK0Re1_YJX5ZnZDWxzvA");
		hs.add("sih8j621A66QoiUFues5qQ");
		hs.add("1vQLTKwmcmZXtNzfKEvMmA");
		hs.add("xgK6AAhJ-cYBUCSaLzgTuw");
		hs.add("eaqJQP6bp7rQJQt5KqfvxQ");
		hs.add("kaIue7GRCmkPzDeHDBTttQ");
		hs.add("-3WVw1TNQbPBzaKCaQQ1AQ");
		hs.add("cBoOvUP2FZxLNG0yh3bZVA");
		hs.add("OmxAvtMyIvCVm16NFIOOUA");
		hs.add("T9iBSa4pxYXP129pHlt5Sg");
		hs.add("Te_i6EWlOJVdQpuELBABhg");
		hs.add("MUFYutWoNsC0V9bSUGof3g");
		hs.add("kr9gePdA-ds4ltXLlH3M_A");
		hs.add("OdNwrZgfPp2Xkj8lEPMJeg");
		hs.add("oXup5d96auPpUOBh5YBeyA");
		hs.add("naUQ_ZHKq2ONBwW5EhJXJQ");
		hs.add("bkbOmsZ9cOggOnpKsxOyiQ");
		hs.add("FV0BkoGOd3Yu_eJnXY15ZA");
		hs.add("z6vO1HR8L2iW4avr610XKw");
		hs.add("UI8iKvzhGn2qZCGIqtQqrQ");
		hs.add("FosnBEgugCZfnvBwQbZPSA");
		hs.add("QJlab4DqvBRJPUfg7Vn5ZQ");
		hs.add("Zf7fMSe7yuW727JyikdBsg");
		hs.add("OrTArReTvdVxEKBAxsz3Ww");
		hs.add("QnnssZJOLZquRp0hqeK1dA");
		hs.add("3SnqTPne49E5XSYv7BvYUw");
		hs.add("UEUQS4z7s-DRzQjky92KYw");
		hs.add("WGNzivxscW54VZ2BfeLmmg");
		hs.add("UVBElUlajafZDSiBK2pltw");
		hs.add("Lq6CDJ2yHmMs4N7jscQhHQ");
		hs.add("BUEeOKuTJc4uZAp1A2dEhA");
		hs.add("ZZcKMWza1-GqrmhzFHW_mw");
		hs.add("c12WDNrP2wyQgbnEYDdxCw");
		hs.add("8t80-omyflkywRfu9LPh6g");
		hs.add("40VsC3U_JLufzJ6b5GhXTg");
		hs.add("8-HkVgPClpSli0ug3Uk-sQ");
		hs.add("btp0v0Qk7CmOmuMdt3aqkQ");
		hs.add("H52LFxw13LBS6_ewxCwlfg");
		hs.add("v6zRA0WqOODJjmpvstrpGQ");
		hs.add("H2DbpsEvor9kTf1-8OEwAA");
		hs.add("aqrs7yE6REb5tTqfnlDVWQ");
		hs.add("16orLd_wKfdfh4AxTZu_zQ");
		hs.add("9vv4aOYHeH_uBq_-AI9oEA");
		hs.add("rK9wysMZ3nh6b6dxiG-l_Q");
		hs.add("GjvIDOEhdQB1oPrFeSpxBw");
		hs.add("lrrW5UAXn_FPQySynu5DrA");
		hs.add("nLn4yNELpgpWADSHdIcCsg");
		hs.add("0mPrp8m_caTxdSGfIxNtTw");
		hs.add("Oqm8u_eI_LVXOMAJ4wzP9g");
		hs.add("X_unrEd0DOcR-FfzHT-Tcg");
		hs.add("mUjz-5FAYqt78l7vVUqokA");
		hs.add("xH4u83wqnR_q13GBcPTyLA");
		hs.add("WJ7rJxbkXqr62koXzR8tXg");
		hs.add("ivKQXW61dlcgoOGzN63S7A");
		hs.add("Kfbs3K37ZczrOQnoxgzNkw");
		hs.add("et-odMgalfrBGzhuMWoy3Q");
		hs.add("_rrWTz0W1K_eWafh-8r3fA");
		hs.add("DtrACWjoGtx4lAaNfxHS4A");
		hs.add("sD38Tp5O4W06Bx-DxeW9oQ");
		hs.add("JauLZ0TL3D3VIGtSnStzhA");
		hs.add("TCIVUf1frqLehZbaUnuQzQ");
		hs.add("YCCDMLcb7UW8G-o_HsWiiA");
		hs.add("XVsN0qYTKj-bzVBGsYnTUQ");
		hs.add("HkSyssTd5_QNNeGI0-ltTg");
		hs.add("hklixCRElEQWkYrmPtwrqA");
		hs.add("cRfn_vMQ9YExuKb378CwjQ");
		hs.add("kTOgIUZPf7cWbsKS1SpO-w");
		hs.add("SPsunwGprmSE8v1Khqbutg");
		hs.add("PwxvN0SnAGPdqXdNEYVT3g");
		hs.add("D1T1jtCfTfXD-cQE3QViow");
		hs.add("FI4ns6iR4ZrhoaYjITf-Mg");
		hs.add("_6gbnNRPIc-iM_0cBLPX1A");
		hs.add("XU5Fb3TosXDUJcNRWQM5cA");
		hs.add("tZCIC-GWGYS7yh3KVbRnlw");
		hs.add("ed6RnUHJJlyFnhJpuiHpKg");
		hs.add("1uMpsCZjnKHEaPdrxAMY-Q");
		hs.add("IQir8LAg3twHUpyTFbKzsQ");
		hs.add("ZniYUcAEcI_n8yxz_2Z1Dw");
		hs.add("_Bh7HA8P570v2DIsltppZQ");
		hs.add("lK35BgpjOMXwchPzqYWomg");
		hs.add("ZP6qFq7LUh6Tr7WHPoOW6g");
		hs.add("25fxw_jOqZtJwl18cCarIA");
		hs.add("aGbjLWzcrnEx2ZmMCFm3EA");
		hs.add("itFwrNtjrQL5NPMYTeD44g");
		hs.add("QDSPPfiwdCDkmpqu3Sshbw");
		hs.add("Je396Ev-dvAvl3ei-O0EIg");
		hs.add("FkeUYSL_PeKv6KbaAWYSqw");
		hs.add("kT_7_6nj39hV7o98c8WLbA");
		hs.add("3KUwS1FedV0_L5y_D9YAiQ");
		hs.add("_PFMtwWXDmdCmgfGWq2b9A");
		hs.add("XmdTkxKyJd7TuDLoiic1kg");
		hs.add("Ln34kwDUNZPLhVhUqauLWQ");
		hs.add("O6fEzyH0fRP7r8IbSnCgoA");
		hs.add("5W0WLaM5gue42MQPpcB0lw");
		hs.add("UYHa5iKUddnZrlxF7taI0Q");
		hs.add("dbh72sNyNeHUgJqQye9Vbg");
		hs.add("zoHCkEiIKfXiLTKUqKEojQ");
		hs.add("1oFvqm7eSpJbVpxpPxueaA");
		hs.add("DqzyOJTJXu0Iwi8og5DJDA");
		hs.add("_yyHTeCtVOQKjD6G6GO_lg");
		hs.add("90cuR5lcs2fJ2BwAA18zSQ");
		hs.add("vOCmoA6cvhlA5bcATzUR0g");
		hs.add("lIZIzyPMiI76KD-oYTAo-A");
		hs.add("ZShuQrMfLOmnUQbLP3dwpw");
		hs.add("mxrXVZWc6PWk81gvOVNOUw");
		hs.add("4qOPELunTvPQsmmnLDr4Jw");
		hs.add("vAOTGsBMJp2ebRCJ6Ny7NQ");
		hs.add("TehSM5JrMRikSnjnnfulbw");
		hs.add("h0Bgl8mTLQCWakpjCRH1fA");
		hs.add("m6l-NYfSXe1nqxZShVstIg");
		hs.add("LcyRdze96F97xuiV1AG2eg");
		hs.add("NERLJXacJ3b6peiZ8ceeqA");
		hs.add("CvRGjwCsrQs1DYYL3z8R7g");
		hs.add("tFU2Js_nbIZOrnKfYJYBBg");
		hs.add("4EhFsjWBSaSp_5TkkLp7LA");
		hs.add("vaq5SJubaZjIoGhgkwxxUA");
		hs.add("KlAARyLySLdoyT8QxJFSIg");
		hs.add("UL3OMN_c-NXHlyb97pDifA");
		hs.add("45CkLZEIYK4KLDAb5GvxEg");
		hs.add("9Bnc9YP0n5cR57xkP6fQmQ");
		hs.add("kAXwEMkpcKMObw45QJGqnw");
		hs.add("_SWb6l-M_ohosfSmet3e1w");
		hs.add("n_d7HDsTdLc9IWwuPHBNlg");
		hs.add("BFZHdg2TRrgw56CyqkSryA");
		hs.add("AqdFUHo_is8NfBh_n7tlHg");
		hs.add("_agqgl4kkXu_5xKCKP8gcA");
		hs.add("Pz7SWZQhxL6ZbhL9jE2NTA");
		hs.add("k8bSp5BfCNCKqTXcKALXtw");
		hs.add("jVgtPnzXvZQOCCIUPEBktA");
		hs.add("ZeJArxfvuV1rAAGT5Xe5Yw");
		hs.add("moXWAu-8-kZqJQ4XV3zhlA");
		hs.add("qVYpYB4vSeijG8J01fOcEQ");
		hs.add("LfKPiwth-lGmCKTxlDoV9g");
		hs.add("_FBnbgbEwaZshbuoUoSBfA");
		hs.add("riIpmJ8cgVZi9-mxYq5L_w");
		hs.add("_ED-tcE-bsR7oFYWZwvUAQ");
		hs.add("j_Mfxog4RUlv3J3KSNRWnw");
		hs.add("mI2poz7WNXEZtJpY8NAUGQ");
		hs.add("vSUWVBPAWFtZT88ff4TEww");
		hs.add("EpkR4JdE5UuNexHbWXsfig");
		hs.add("gc_nRBbdk4OFWlY9ztz6tw");
		hs.add("DXut5Gke7XM6oAvoFahFNg");
		hs.add("6nfTUgP3UvQ_jhnT8kCpew");
		hs.add("uY1hOM4pySx07Yle9NGAiQ");
		hs.add("Hieqsu3u1peZ2I2jPwiKHw");
		hs.add("hZRFKGC7NmRxwiIqWTeRFA");
		hs.add("jiXsSkXDx60rafcprwNqpA");
		hs.add("pJwfUoqrSmn4DzKvYPG15Q");
		hs.add("QbmcCE_cLq4WO8ZMKImaLw");
		hs.add("wNUea3IXZWD63bbOQaOH-g");
		hs.add("PXviRcHR1mqdH4vRc2LEAQ");
		hs.add("GARb9Hk4Y0YTjBl70DniVA");
		hs.add("ljpiBFSGgOobhrLVmSbQeA");
		hs.add("X6kiOY9Ki8KXZjVHLro05w");
		hs.add("WWbPM20A8agePy7-X_6AlA");
		hs.add("npfVfumxVAkQNYpY1fSvew");
		hs.add("wZxrcIHmkhT4OHvIxPwd_A");
		hs.add("Pg8OPh1D2ws0xO-I-8ppoA");
		hs.add("yOKNzOST0WVaCMZiUceK3g");
		hs.add("Vm_P0F8OfpXlW1rw0eLoMQ");
		hs.add("MRObvlfMLEhz9szPTMkGwQ");
		hs.add("ffVx7PrC2JSfOq_DTW-vZQ");
		hs.add("uoLKwJeH1rWeqUC0D1La2g");
		hs.add("mDdqifuTrfXAOfxiLMGu5Q");
		hs.add("CdihJLYPU5TqhQpxbuuO6g");
		hs.add("J8Z90BG7gkFaaync8BQjHA");
		hs.add("leEhsPA6NKRZ0CAKdmJwWQ");
		hs.add("-4bNlx03GsXzgkHZwTrMaw");
		hs.add("grjeZhCQt_C72ZTPQtD4gA");
		hs.add("L2xegOESPgM-MpMNT5NJfA");
		hs.add("sJ9omljhmwCOtwYEQ-kbnA");
		hs.add("ZOcfu9B5657he_gBXVeIcQ");
		hs.add("KcWUgvyl64Vp0PfwQRZQkw");
		hs.add("uEv5oBGUSSiuLqSbbHQQ8A");
		hs.add("mpDxBBGywUE6GRRKja3sBA");
		hs.add("SKLw05kEIlZcpTD5pqma8Q");
		hs.add("DlCtdbceo4YNSI53cCL2lg");
		hs.add("Uov4o_7gRqQKQyjVhWOpVA");
		hs.add("O_X3PGhk3Y5JWVi866qlJg");
		hs.add("LdEzAYCufZMTbWc0soCaNg");
		hs.add("pQAIM21Yw4eNdbha2Rxkcg");
		hs.add("sItVzx2HXJ0Ew5xbpW9Axg");
		hs.add("jsO9c15l1KJ5ncBid3pnmA");
		hs.add("Naj_zcvl1jwORIGv-TDbog");
		hs.add("pyrFpk2d4TT9PYG72Mrj2A");
		hs.add("v5mjUyUZeWfLTdxXfZYKMg");
		hs.add("QweOrPB4d80XnWtESAl1kQ");
		hs.add("fF6m3qsD5blnwuZRuYhzWg");
		hs.add("EcHuaHD9IcoPEWNsU8vDTw");
		hs.add("baV9mE-cD9u-buA9N_k-Xg");
		hs.add("gw-zDohfYJ3_RDlDd3faRw");
		hs.add("TwxHMCcRdF_CQb_EZ6kPQQ");
		hs.add("EnKI5w-x0_ZPAS_3QPYFtQ");
		hs.add("kpdLm43TItSM2415L_V1FQ");
		hs.add("nQUsMhT7qY6pPMvTT6xGcQ");
		hs.add("4bEjOyTaDG24SY5TxsaUNQ");
		hs.add("zObyDUjiXSTCXa5t6w9ghg");
		hs.add("i2gLXa-MSAS-9oU8K_rnYQ");
		hs.add("UpMR63WZgIn8VDKnYpDwXA");
		hs.add("d6eqlH4tKE2VmiTPN6TOEw");
		hs.add("oXKPSI-RUqOvmuSCh_DEQQ");
		hs.add("Vtx0VYkybAd71fzwgaoQ8g");
		hs.add("j2a5uJz76rK9uTRgLn5TdQ");
		hs.add("iAmIyYVuQ8rDfbM-serqHA");
		hs.add("VtgBj2eu31O5aU3fJI6CHw");
		hs.add("bQFhCrHnUuoB8XGllzObSA");
		hs.add("t_0576Esa58pcLHCEpj31A");
		hs.add("U3AUN4Azkm76qsEaWqOCEw");
		hs.add("lPh02W25cOrAz57UbTpbFQ");
		hs.add("3MmHmJXr8Ltk_Z5EGE4KUw");
		hs.add("79EG9Pv0bxNTmBjTVCd4CQ");
		hs.add("cJbaH81HP6r0eHDy8_738Q");
		hs.add("AaKlegu7gmOCD4rEESF76Q");
		hs.add("Dbdj-Y3uBydiQUqpaqgSmA");
		hs.add("xTluZ-CVz18esCjeMxUuGg");
		hs.add("4sW8Z6NLXLRkruSKSKUEUw");
		hs.add("9lF6-JrS2PvTkw9KVxn3Yg");
		hs.add("AQyqlSpv0o9jCPSoP0PpfQ");
		hs.add("UxiSHVZxMdey7vRwm1fQyA");
		hs.add("KdDHF8nFUVvR2pBN5ruGFg");
		hs.add("V9i9LnTg9H2XvzqCVBSOXg");
		hs.add("GAPqG0WNBBidKeZTMpEZ-w");
		hs.add("8Pzdk19tA2bKlKDSgwWqoQ");
		hs.add("H75yc2Vp7d8wuAe339DpOA");
		hs.add("jJiN_GXWFcYhQIsK9gTO6Q");
		hs.add("CKf3mf7fl5sZO9xviHU7lQ");
		hs.add("_qvxFHGbnbrAPeWBVifJEQ");
		hs.add("fsL04IyN2sIMEU9kNQPJHQ");
		hs.add("IRQNOYVE-AyjCliZa_3R_A");
		hs.add("F8ljll9IJhgUmOxUshlqiQ");
		hs.add("iqSs3u2rlsiCDPu-jWj0Jw");
		hs.add("nJwzIiboAN8TFrIJUzakuQ");
		hs.add("Nqcl3hDLyiwNQBxQpKCdIQ");
		hs.add("Oq01QS2G1OvCsunccVSgxQ");
		hs.add("zt1TpTuJ6y9n551sw9TaEg");
		hs.add("gWRJ_Zyl2gtx_pCNTKnG2A");
		hs.add("5kB59vuc4yufpGNNrF3Efw");
		hs.add("_-9pMxBWtG_x8l4rHWBasg");
		hs.add("egaieBcnSZLYGl1N-_CtvQ");
		hs.add("Cu3L4mNS_Np34wD7Af2fCw");
		hs.add("2q1JLqJ7IIYXONhOKJKoGA");
		hs.add("EF5vR_UUavzPjtgMYFCg5Q");
		hs.add("U97cOaXPSOGmVhKEomPjlg");
		hs.add("4eWKhiixHQcEvQpwIPvT0g");
		hs.add("C7EonfwiWEOVpwuGWchJSA");
		hs.add("lsF6bbPFM7USmiSIyOaCXA");
		hs.add("MSePTzl6B8boCt2I3hgkMA");
		hs.add("5nws-cXSlaCAGoGZ37bQGg");
		hs.add("WJJFtykb2VAlKAkwsKhy7Q");
		hs.add("10RoUv7N_K3amPyJ3Ao2YQ");
		hs.add("4eqw9xCbCmNQPV-AQJcXPg");
		hs.add("6PuVFIL1rF5E-qu0Wq-Gug");
		hs.add("bfANvTlrA7cpgiRoYjAc0g");
		hs.add("CChwRoYVXA3QZulS8a6xOQ");
		hs.add("KPoTixdjoJxSqRSEApSAGg");
		hs.add("R6aazv8FB-6BeanY3ag8kw");
		hs.add("hqVbmZNLTdR2y7G7oJu9vg");
		hs.add("SgTjnyElc26gPUghVuCuSQ");
		hs.add("eCDUWNT1iQHrhb8JzK1M0g");
		hs.add("632ieN9WlWR-3bG5Uug7Vg");
		hs.add("lAher1puKzN9r3LALx-JqQ");
		hs.add("Gz9jnM72ouoKcfGtwzrR6g");
		hs.add("bXwFv2IslBSzkMPFkS_aLw");
		hs.add("ufOY2lQHDgSvou3YLT8gHA");
		hs.add("GzWiVvE6JDdBNowNVshItA");
		hs.add("B-urUvRjp0GJ8-Kos2Rjrw");
		hs.add("LRLN1CIUprYLs6rWUC5bAg");
		hs.add("QvRK2dyv4EDxuJ-LuodE2Q");
		hs.add("5kOYuJtRjAUWZGDkP8vnRw");
		hs.add("d3ni6cKglu4L3JeveOqQDQ");
		hs.add("RhOTBt7ISr2rhXisSMLTSw");
		hs.add("HbUQ_3dlm3uCacmhTEMnuA");
		return hs;
	}

	private HashSet<String> getBestBreakFast() {
		HashSet<String> hs = new HashSet<String>();
		hs.add("b9WZJp5L1RZr4F1nxclOoQ");
		hs.add("aCMhR8XTu-f8GgMHYl0ipA");
		hs.add("4bEjOyTaDG24SY5TxsaUNQ");
		hs.add("SsTxjxo8qvqBMvan1rzNzg");
		hs.add("tFU2Js_nbIZOrnKfYJYBBg");
		hs.add("CZjcFdvJhksq9dy58NVEzw");
		hs.add("ntN85eu27C04nwyPa8IHtw");
		hs.add("tdeHd2AVYlEnz9F1UGb84Q");
		hs.add("vW4G1hwiW6LkuhAfbeRfqg");
		hs.add("1yx2zLskVTe5WQdYjL2Apw");
		hs.add("9BJ5h9X1krpXFjKj0a6wbg");
		hs.add("xfwRO04KbAPw_zRotCfWQQ");
		hs.add("mdpVpp3YjNM4OOeIcxKyfw");
		hs.add("rwgU2XEFJ7nyCHvUnEC5ww");
		hs.add("hJxzqajebKdt2mgiC2YNSQ");
		hs.add("vEeiIvhzz29rO-6EPFqkjQ");
		hs.add("HDvCnqIf5twbMb5-eG1EJw");
		hs.add("1zDCfNgtfyh-Uw8j3JxhHA");
		hs.add("sBAueq0jUmlIH6vdgyP2aQ");
		hs.add("a3VX8WpAVt29VNlGgYJxrA");
		hs.add("2K-XaFjaHUR8Dp6QAihITg");
		hs.add("6Tt0mGKbMoAz1GsjkVhbMQ");
		hs.add("R0MhNwopWTWXcg8CPAFgpw");
		hs.add("0CG3ns3gwWV5nOnfzSfUIQ");
		hs.add("9xGeYICHI3UoTcvlIKwWzA");
		hs.add("udjYDN0FvSs6bNGXb7Ppcw");
		hs.add("7lSQXiyPGrtfnCg8ym1Kmg");
		hs.add("CfkVs26tVcosDI6IDxKs6w");
		hs.add("l-gU37t21eCm_UU7XGU-8g");
		hs.add("L-uPZxooP_ziXCtRrWi8Pw");
		hs.add("OSL98Keoc2FSNx4a3ge5Uw");
		hs.add("JRzrqJmsQ5AZ4bMQLUfyHg");
		hs.add("K8dQr_82-DMpDudEv8PDmw");
		hs.add("RhbOa-Ft3sZB4B_1j5LfyA");
		hs.add("YnKGPO6hk_ig3jzzsdfwyw");
		hs.add("W8AYXV_V63ke_p1SE44-Cw");
		hs.add("4YfXP-NxQXntqi0qAknU5g");
		hs.add("M8a29Glk1aG3iYPKpckaIA");
		hs.add("Cz0McL5lUaihqOIw0_Yo7w");
		hs.add("Sz46GVteyTbGQhA76HmleQ");
		hs.add("qE5Q3Yj2Up3wewsh1NsTuA");
		hs.add("QbmcCE_cLq4WO8ZMKImaLw");
		hs.add("XpXb1TfN8610d9fd7_GaLQ");
		hs.add("tUMGHqf05yRUsBuTAoVToA");
		hs.add("y6NFyThUU2wtTNa0rX7VrA");
		hs.add("bxEd1ust_wI0Br-HLnEy0Q");
		hs.add("3oLy0rlzRI_xiqfQHqC4_g");
		hs.add("UCEAhciqe8avW1N-bWJ32g");
		hs.add("LCeF1wK5OqP3PPEVBa5Xfw");
		hs.add("kfscAJnLVf6J2uEte7g-5A");
		hs.add("zNzJkzZxPTeTbRIRfeU9_Q");
		hs.add("PNThcRNEFI3azvfhvhd_KA");
		hs.add("4r9-iKOagzn5oUvPE9Bz4Q");
		hs.add("EMGkbiCMfMTflQux-_JY7Q");
		hs.add("MRUsPIVywMFDZHbfDa6YjA");
		hs.add("GRFunGSUZxXqNCZJrN8Oow");
		hs.add("s93PtWxihLbhK5Jg_FttzA");
		hs.add("0Rf3R61n9Ac45mS408n4Ww");
		hs.add("pPfQ73--Y_h5Or0aqDgEGA");
		hs.add("3st_g8-2-ZgQhJ6N_174QQ");
		hs.add("EXtCgZoxHNjXrqPCFOgQmQ");
		hs.add("vWU4I-1g-Cf9w-aWeNCuRw");
		hs.add("W9C2sZjq-1QQOJrTSFxUQA");
		hs.add("ZP6qFq7LUh6Tr7WHPoOW6g");
		hs.add("4X_XAOeMw7AFkYhg3NINJA");
		hs.add("t80qleqEIqIyekB95IrAOA");
		hs.add("qT4w8n27RBQ_slz_FiK0CQ");
		hs.add("hcfmPMH8-5ZI85R6dztehA");
		hs.add("gcyIy1HxSZt3ixGIOtGzcw");
		hs.add("31Ix66CdEqyiNJ77XuoXyw");
		hs.add("UEyXv6C3CyxVYmxRDWYgUQ");
		hs.add("tv3qQk43GgNRxhu5LK2HXw");
		hs.add("WnBSlcek6ACsjE0UDJ1l2A");
		hs.add("2Igiyhi82R8_QaaPplRmCw");
		hs.add("cbLaFQJOfzDy_TxMkPee9Q");
		hs.add("yV-eB-pQVeWE7W-WPC8BUg");
		hs.add("PxeX1M8WtyPxX1MuuGIh-g");
		hs.add("ygt9aCJ3X8m3M4H8vU7cSw");
		hs.add("oSDf6BHiMlKGZdFFmIo6NQ");
		hs.add("L9UYbtAUOcfTgZFimehlXw");
		hs.add("a01JeGRdPYArzDgBLP9M5w");
		hs.add("NfdZgoNTGsfth9MS8Qaurg");
		hs.add("eoDEx1GGQA0CBDhy2ql_Kw");
		hs.add("kr9gePdA-ds4ltXLlH3M_A");
		hs.add("_BQ5JOUWDRgBXNylMSVpOw");
		hs.add("5w-qVzxUOGEajm9eH3gEkA");
		hs.add("7_y_M5wRaSvNXt-q4xvlEQ");
		hs.add("qdA4qiSXjaiuqO4SueH9VA");
		hs.add("9Y3aQAVITkEJYe5vLZr13w");
		hs.add("V6BYjHM9SnXscfkln3hCdA");
		hs.add("UI8iKvzhGn2qZCGIqtQqrQ");
		hs.add("woeY1YUkcaXgx6CzWqhATw");
		hs.add("fkVBloMEFJG2HTgeCxeNDg");
		hs.add("tqu42L0qXzkvYKSruOz0IA");
		hs.add("aLWvaNTOUr1wdOizitoOuA");
		hs.add("co0vxQ8ecXiBy2sGDeHi8A");
		hs.add("vvPzcOhbQn5fLQUAIxcP6A");
		hs.add("tbTc7094zwIYAtU-0NkU4w");
		hs.add("jOuERtVf7QePnK9ZcdH5XA");
		hs.add("rBPQuQgTcMtUq5-RYhY2uQ");
		hs.add("nvaAUTTl7oqiJDhuimNG6A");
		hs.add("8zL3V6rmFKBess3bxPLAoQ");
		hs.add("R1ySBCVS2eQf-s0Z4ifIug");
		hs.add("QnAzW6KMSciUcuJ20oI3Bw");
		hs.add("SZCF6Tm-9jeiHQH9yjeHXA");
		hs.add("1F-pelV0fTduYV_vCrvjLA");
		hs.add("LQ8xiZao4z6hn_l1qy6Jeg");
		hs.add("8H-ZzMp0lvc_4GkrAxi3oA");
		hs.add("L0ss_FFm909s8wnTw0CG3A");
		hs.add("GkhAze91Q6ImrZDTGT40Rg");
		hs.add("NN2qs5B713vM6BDcMyrg4A");
		hs.add("70CEMhOtK-l-7IifDvTlEQ");
		hs.add("r7FsXCWuomxjurxwQINnsw");
		hs.add("va8gX25HcEcnHnLgy1j_tA");
		hs.add("SXVI_RMuNWEoXDXlgtRfiw");
		hs.add("zfY68t7nVihCwiCsCgM6cw");
		hs.add("W9NvpbO97Bh0E2vyj-87fg");
		hs.add("sbsFamEj5wDxNAjUKrMcSw");
		hs.add("dBwSs6INAgTipopffoCwzw");
		hs.add("NCeKp7rHZkAzx7CAau6ymw");
		hs.add("BNTw6sX6fDWe-pmyY1FeDA");
		hs.add("Ky6490ndvfhU11eE7XcPLw");
		hs.add("zt1TpTuJ6y9n551sw9TaEg");
		hs.add("P5nqpZIxAhkBxCLaYwyaig");
		hs.add("py-GHWztjFhria6RZs9Q2w");
		hs.add("ieYiud3trM-9e7E8YUhK0g");
		hs.add("JUXPQQshoOV5LUKLtCrOtw");
		hs.add("l593y9KEguq1JWVFcaL1DQ");
		hs.add("EFSU5EPU8VsZmrjbTxjc4A");
		hs.add("77BTvEd_YG_2JUSWeDmGwQ");
		hs.add("RaI4NZfESHbCPu-7Vjv9rQ");
		hs.add("DO3XP1OOGqaGycUcSdtZ6w");
		hs.add("GpeW7WM7M6nfwCgnnPiqqA");
		hs.add("8q957qOv1wED08Rgs0-VGg");
		hs.add("9I7aN_mAByif-jstzclb4Q");
		hs.add("PbvL3Ay5PnyWbgXZjrN9pw");
		hs.add("34TBKRXYq1JHe4kYlHW2Eg");
		hs.add("PVooCeYIrp9E2rtrL4R98g");
		hs.add("R8VwdLyvsp9iybNqRvm94g");
		hs.add("2nzUx_M8Szyzsf4CszHasw");
		hs.add("IM-9thHqQbBK5tX5MfTzBQ");
		hs.add("dNsKB5LA2Mf8BDqTS_FAIA");
		hs.add("wO8c-FbduauxCGiEHchGRA");
		hs.add("-1bOb2izeJBZjHC7NWxiPA");
		hs.add("qW9UysjJw3y3CwEbzruEEw");
		hs.add("NERLJXacJ3b6peiZ8ceeqA");
		hs.add("M2SjLXsuAy5RNKwxaA5E1g");
		hs.add("53YGfwmbW73JhFiemNeyzQ");
		hs.add("btuXBnJEIkn7ax2TfvHQyw");
		hs.add("oLqW-x0egbOi0I8uOZ7Gwg");
		hs.add("cB3P1HylsRlEIpWWsRJR5Q");
		hs.add("9dn3AMdwvD2KXnTr6AJY1g");
		hs.add("9yKzy9PApeiPPOUJEtnvkg");
		hs.add("Iube_qb30CQ7iRBefxFs4g");
		hs.add("pa6K7DGByxBXxcVJ59nWMw");
		hs.add("LmbVSU7Diel5lR2b6AS5SA");
		hs.add("AaKlegu7gmOCD4rEESF76Q");
		hs.add("zN1pDCfcvti11jinX7ahVw");
		hs.add("3FHNMT6IX1j60cutRxkKCQ");
		hs.add("UW9q_26cX8fKqtO28n78AQ");
		hs.add("Qb66eJjfC1wg7z4wgKrhsw");
		hs.add("VKjRWRdiylULbeaMaa4-Zw");
		hs.add("kcX2_M5YoM6-SqVKMzPceA");
		hs.add("5Km9-1qGEgrOOSeDfZdTRQ");
		hs.add("oQfCWtO5-fGTFrclqCJOwg");
		hs.add("qt0Bh6qo2-zxMyFXExyt4g");
		hs.add("nIX7WiUPekK5YpiRQorxlQ");
		hs.add("lJe-zPM4U572nVI0eAN4Fw");
		hs.add("OllL0G9Kh_k1lx-2vrFDXQ");
		hs.add("JpZG0xheLwuAwj7xzoqx7g");
		hs.add("Az85N0Z4OKxOAzGdigi1nA");
		hs.add("GFsy9RWmPt1qXseS67Y2UA");
		hs.add("L2g-uehAggLddHkd2xHZYQ");
		hs.add("udYZ82zdbH_0Lh-SihLs1w");
		hs.add("vvMR0jgDoBA-g1XgZy8sEg");
		hs.add("MC8Fv4Hd4reUsTKJYoZPfg");
		hs.add("z2gP9moC7j-OgM0K7Au9uw");
		hs.add("BAbYfKQaQImLil6xqaOFyA");
		hs.add("kVuzYAB0U-ZYJiY56flz9A");
		hs.add("bZkRR9-BnwE-sb1ql7WPJg");
		hs.add("vaabk6CYXX1dYVQ1xkyPUg");
		hs.add("8rztpAGPJA9fgFwP25RP7A");
		hs.add("JV-B-ZDwgA54utmkeG9Aug");
		hs.add("d4bXnfbUc1SLu3jVcr-w1w");
		hs.add("6LNuxmnwiTvxXEDk06MkrA");
		hs.add("kmZI3pih60oVgSGKM2OERQ");
		hs.add("wdCE3h8JECzE1vfU1t2TwQ");
		hs.add("o_wRqOpli9kyZGXlJtLLdA");
		hs.add("UzMMpUFwJhwUkHOyeXeWsQ");
		hs.add("6HKjKhgDLBpuZFNBOCzVQw");
		hs.add("RIeWXLMHZQlYprYt1x2f1w");
		hs.add("EJkiV-vOO2NfQH71KeqaXw");
		hs.add("nyUdKma0UUQMjqa6BaXVlg");
		hs.add("A2aVN_Yw3xDz4x7gGtmYog");
		hs.add("qKZzLdcMouXji7YASALbBw");
		hs.add("tpnEAM1bfOpz79Lvf6SmvA");
		hs.add("ioXu3MhPt_v8f5wTWJX4ag");
		hs.add("x6BemTnk7_eCuvbv5MflWQ");
		hs.add("4N9fHxDrX_MgrTxvmbOWkg");
		hs.add("2ceeU8e3nZjaPfGmLwh4kg");
		hs.add("cMBZ46gNJPYY7zkxDb1piw");
		hs.add("3rwM9fPYPk9qDkEBOhyHbg");
		hs.add("m_9QMfvVYFKsxPjlkCvZqA");
		hs.add("YNQgak-ZLtYJQxlDwN-qIg");
		hs.add("b6ZagkhPwEwQCDBB7KkVPA");
		hs.add("0InQd9vuhRc98OksC3Ks8Q");
		hs.add("qmIT3LC-kMNiOy7_XpWNUA");
		hs.add("mQfT3JYu18HN22DVylcE7A");
		hs.add("Y-9dJvw-J2d9QKfuL7mKgA");
		hs.add("gas4eqbnp_dzdA3kith5XA");
		hs.add("l67DVGeFu1BA5b2QIwMqAQ");
		hs.add("VLON3ZLAZm5fSE50_IC_Yw");
		hs.add("9GUN0cEAK6ysOz0oGhCK8A");
		hs.add("e8FMAuTswDueAlLsNyLhcA");
		hs.add("vzjxe7mMtwlxIA9aBlxKfQ");
		hs.add("0DvsBDG0CEwIK8uQxUGiOQ");
		hs.add("9ao7DSa0vgDMQqrWtEcwnQ");
		hs.add("kdwGeJlYwmqt9X49IG49mQ");
		hs.add("nts2OALwvyvfNh9focRZ3w");
		hs.add("vTnuOWm41T1iKPNJ8PrtIg");
		hs.add("6EpmtuLKE_fqVE1mDILD1g");
		hs.add("5U8tIBprXfTYCKzMLlIA7w");
		hs.add("m4Cj-tvXZDwAU4IpqX0nPw");
		hs.add("_gzo4jScQtavLCHzJo905Q");
		hs.add("pTg5vc5RuY3SKWQX_NB6ew");
		hs.add("pqkwR2me0LhEZulRcQpOuw");
		hs.add("M0Ulu3PzwBumgOZJL-6KnQ");
		hs.add("3JwsrgkmQCEuz17WOB62eQ");
		hs.add("osixLFHD7OKEUy2HSbN-7Q");
		hs.add("ZEdaJ8mcMpPiFWgDuSPqeA");
		hs.add("mggmWBv-RHAL6iCdwRGP5Q");
		hs.add("3xtsKiY-vUUa3yWrBhYIqA");
		hs.add("1vl4-5il_LGtDRxUCy9ldw");
		hs.add("uXu7hX_bTrr-48op0Ykkyw");
		hs.add("noX7tQCO-zYkJxVqoZ4u8g");
		hs.add("ateowLnq6kpgNNWHzCDByQ");
		hs.add("Cun_PbjTnPdfZRZAd9wx2A");
		hs.add("TxKmAsKQjND5vbhBdUSyIA");
		hs.add("JwUE5GmEO-sH1FuwJgKBlQ");
		hs.add("NLKjSOHL4F6yQQooc6JbyA");
		hs.add("OrXzZB0M0DbPXx3F_X6GkA");
		hs.add("3vKhV2ELR2hmwlnoNqYWaA");
		hs.add("T2NesLFF9Xhlho3iw8i53g");
		hs.add("g5U8omEQje5lRx4EherR0w");
		hs.add("J3A5V0Hl07o_KQSI2hHf_g");
		hs.add("K8pM6qQdYu5h6buRE1-_sw");
		hs.add("KXMfiG_2_LALAaGzxt1YbA");
		hs.add("AyvyWENKpPBOFnFFkZuAyQ");
		hs.add("fAJM5vQ4dJn2xSfWMAEu-A");
		hs.add("u9wjRhUjySkHPa_hG3kFOg");
		hs.add("bUEcGqSBzcoofYo4RSr-AA");
		return hs;
	}

	private HashSet<String> getFrenchToast() {
		HashSet<String> hs = new HashSet<String>();
		hs.add("b9WZJp5L1RZr4F1nxclOoQ");
		hs.add("tZXPhvufHhfejGrRp554Lg");
		hs.add("GAPqG0WNBBidKeZTMpEZ-w");
		hs.add("J21k13gcA8-qi0LGJitThQ");
		hs.add("zt1TpTuJ6y9n551sw9TaEg");
		hs.add("J4WPiHHlzqrKH4amrFxefA");
		return hs;
	}

	private HashSet<String> getCheapBeer() {
		HashSet<String> hs = new HashSet<String>();
		hs.add("UsFtqoBl7naz8AVUBZMjQQ");
		hs.add("rRLLhMPgBXrtTDvOeWHZuQ");
		hs.add("CiG5CvHxYQl5DZ704a4viA");
		hs.add("1Kuuu75LVwr5-1OQ3Zv71w");
		hs.add("1fSlarYpCHK7gGeQ02CiMg");
		hs.add("aRSfth72sJgpSN2P6rm7sQ");
		hs.add("GjsA7N1j81TjBt7hT5H4YA");
		hs.add("pNyqk-HCo3SXPPppi04Bag");
		hs.add("d3-h8QpXoQnUlC9nt55HTw");
		hs.add("kLeXxdySJ0Arrs3NWK2itA");
		hs.add("oqL1hS934CyZc3msupQNRA");
		hs.add("pS5WsUlWOVAPM0S2rVI-SQ");
		hs.add("2vsPceME9rHNZ9OkR5zrpg");
		hs.add("CLW4LJCYbAkwlgNWB2rVbQ");
		hs.add("OzB1Hv1A8Lz_V4hYZ7Duzw");
		hs.add("ubWxOCe1b0pGg2Ztd4-hXg");
		hs.add("cqIHyZ3Q0D4vBi-vb4mi-g");
		hs.add("9mQj65SmYj2pcehH339aEw");
		hs.add("sHac5Efa3ZPK9GpeeHvylQ");
		hs.add("strMzTo9IsGhUVBkcB73jw");
		hs.add("62F17L8z4Q4S7U_TayuDBA");
		hs.add("hGQsnkndreW7b26XC2HVRA");
		hs.add("eA-qHFglOMhHwXcnHBRpNg");
		hs.add("yW4XOMS4biiSXOwkbZ6wpA");
		hs.add("chudEeZo1SNr-0Mo9L2OgQ");
		hs.add("L2J3JfjXZLnX1rLhWKthqA");
		hs.add("PLSEnkN4XybG_6qJi0R27w");
		hs.add("sKmclh-d2gJkzVVbLdTgtQ");
		hs.add("d53YK5c0OczXpDCBijbJLg");
		hs.add("fRb2pObaOLUI4CgVVXnm4Q");
		hs.add("OvE1oiSg9gaB9cLGzBPlnw");
		hs.add("6RGD8kxrLwW1PztxZIPXlQ");
		hs.add("tqu42L0qXzkvYKSruOz0IA");
		hs.add("NavcBip2CJFK1yEjnu3HFA");
		hs.add("Zf7fMSe7yuW727JyikdBsg");
		hs.add("YQUi5zzpACd0tgGQtcKyYg");
		hs.add("LcBWyVrCN49IOvkAPNPmZA");
		hs.add("4WibRASYlCFmu9LcaVZRIQ");
		hs.add("yhR_thWkjsa5V4bMhFTN_g");
		hs.add("JuaQPvvWdbJ1B1Tn0jIt1w");
		hs.add("0UZ31UTcOLRKuqPqPe-VBA");
		hs.add("vGCetjJwnPU5bqoNxFM3sw");
		hs.add("tHQEAEsW8RagML78cJk0AQ");
		hs.add("r-8wS4RTfRJtWM0DvdaCtQ");
		hs.add("bYhpy9u8fKkGhYHtvYXazQ");
		hs.add("t1sCvl0nSbWeRj0ZgsolRA");
		hs.add("CrlViaCIcMeQuZc63tbdQA");
		hs.add("6LM_Klmp3hOP0JmsMCKRqQ");
		hs.add("SkHb1w-oNPW1hHlzgLb9ew");
		hs.add("M2SjLXsuAy5RNKwxaA5E1g");
		hs.add("UL3OMN_c-NXHlyb97pDifA");
		hs.add("Shy4HqmyEewCLvq7Ub3Whg");
		hs.add("nsZrRPXIfEm2Gyd3nZRyXA");
		hs.add("NK-8zniVfA21IQoQCynrDg");
		hs.add("GM4-aWjgQjxN8sOwff7Ufw");
		hs.add("KFj-E9_30TMy0Ryq3NBEHA");
		hs.add("F3YpaCIygYCmQz2wvPHwUQ");
		hs.add("r9sGMJ084n4IS9eGmlCKjg");
		hs.add("PpPKiJjHap8hn4252v1awA");
		hs.add("V9Rha825Yz3VfMWjfgVR8w");
		hs.add("fZVZeZJkziJ7B1rIcmT3Iw");
		hs.add("zehWnERkDLir0lDxxtVXPQ");
		hs.add("G5I2c2hs33Vy8DUAAkSF9g");
		hs.add("H52LFxw13LBS6_ewxCwlfg");
		hs.add("bfDQai9X59uWK-XgP0t6rA");
		hs.add("7TMf1NuuAdvhG7IojZSKnw");
		hs.add("uyg5_fHXJe837GXd-4yiSQ");
		hs.add("E_TSzYjABEzD6DXsvjZnsg");
		hs.add("SX8GyKnxVaVCfuPZkk2oaw");
		hs.add("adv1-kA6k2N4L-e4zULuNg");
		hs.add("Z2F2FEG0rEVcitxAB3KJGA");
		hs.add("Y3MLyIYY1ihfOjjvY6k3rQ");
		hs.add("lL-JpRu9pv_TMVTQ3L13sQ");
		hs.add("jsJxRLGm8zjWm_HVR2FDnw");
		hs.add("jIW2XVWsuqjKOHFw9rTDhg");
		hs.add("smWlFMgNgfDm8ZUKGvx65A");
		hs.add("j9NvcEFk3V1LWnEQkcWKYg");
		hs.add("DkONJlpjhe5cNxDWrHjHxA");
		hs.add("66XZYUBswb9K12I1FVVi7Q");
		hs.add("oPH_GZyKw_QzPAV-TG0x1A");
		hs.add("J3GNpylZmd40S_StxXMizQ");
		hs.add("ppoP2E7YOZpa2TmarTY2rQ");
		hs.add("1nE6Dwo8rRxXnKToD2S16Q");
		hs.add("MonRZXpZ1vbBtw-q9bfGug");
		hs.add("Yz_5BP77Ml3TaEMycEq1Ig");
		hs.add("jl2eDqw81T44eGJ5PqxCLg");
		hs.add("chIyU8aGX4zct6GJqKWTOQ");
		hs.add("NqelJlme2RN0RxcmO6lxmw");
		hs.add("feQYxrwOTfUioQmiY_USew");
		hs.add("63PpRag4D_8HB9eAzHJg_w");
		hs.add("3l72FflaaeI0tWEAWN3-gQ");
		hs.add("a7tpayb23j4Q4C9yUmCuWg");
		hs.add("wH9WtaTlrRawH_IpK90RPg");
		hs.add("J7DYRCtU9Tdtja5c7k1sjQ");
		hs.add("TFvwZutGJS3LfNA7NKbJKg");
		hs.add("hkKvb6oXxn8ygoP5fFln1g");
		hs.add("EIshA1evDfCTcuI0dYUo7A");
		hs.add("xxZHUf4my1RMwGIp-sR_yA");
		hs.add("JiQrxLpNZwduntKSV_D04Q");
		hs.add("kgqurNLSpCmHqpprJOk-Tw");
		hs.add("WcawfXDP0k8UfLyEoz_cvg");
		hs.add("r8CwFUEQtL8gAT9KHnNhuw");
		hs.add("ET9F32B8mz3q8lNmtDMlcQ");
		hs.add("H-pXhtIE-rRfHiusL685ng");
		hs.add("KlyDLw_ofcSn0v-8uNdRDA");
		hs.add("bUxYCZqDzrSXKayJyM1zJg");
		hs.add("M6fjHpkL9IRI-nI0BattRw");
		hs.add("bmsS7NgF6uYFkmoUaJuh_g");
		hs.add("TsD1cUoAas0Lv0UtT9-sdQ");
		hs.add("FUUXfZfN2NruelWQfQxIzQ");
		hs.add("4va6XKMFJR37HKfY0-wJnw");
		hs.add("cRfn_vMQ9YExuKb378CwjQ");
		hs.add("gEgPQbren8pHSEQp3vqprg");
		hs.add("DjOxXobyGDwWt89q4z1twg");
		hs.add("mXk7cxR0OeZESz8S2q18Jw");
		hs.add("xuuJSD0Wjc1WMIbAIEObng");
		hs.add("7q1FpSXbE6XtLNg518pxDA");
		hs.add("o5Me8uSqyUSm8U3aEMAbSA");
		hs.add("dxY1gl4cO4-rEFATCkFUIw");
		hs.add("9YUe5J_cPCBo_mL7-z9HCQ");
		hs.add("cXtL3_ksBsr6uZy0fp-TDg");
		hs.add("8Cuc1KWo1sLhAaVHxsY_pQ");
		hs.add("eq6lQI039SBLC6sHm3idGA");
		hs.add("qpo6O2Ozbrn8wFnoCM4slA");
		hs.add("IR1vDeNJv6vOQgWdPe7VsQ");
		hs.add("gWZt5lnRQPbTwXRi9Ik6Tw");
		hs.add("5KehfZTO3RoxtvkxEPq2mg");
		hs.add("Le58tt8I6HFgay1qnNG4iw");
		hs.add("NHy-HT-FI305jqgyeIWPCQ");
		hs.add("yJXgPm51sH_WdpMRqM263A");
		hs.add("x4uJ23SPIOPkCxJkmv7msw");
		hs.add("P9pZLGjYc1j7VPO-KIBpMw");
		hs.add("fhe6HAP9_IAMDyH8OEEIwg");
		hs.add("7YL_vXkYJ6EyiQP98kDMWw");
		hs.add("l593y9KEguq1JWVFcaL1DQ");
		hs.add("xz4qczirwLcSrCqTalo7kQ");
		hs.add("v7OwbHgNgy_VQ9eP5FjvUA");
		hs.add("_20WCD89imWx15jlxv7kGg");
		hs.add("qWzxhlUq472AlcFTGNlhZQ");
		hs.add("gCVWxtYREVgirUvlUfGPzw");
		hs.add("m9haUi2_1lHR2eAKBhKwDg");
		hs.add("HV-0vQADkXSKqFCz9HH7vQ");
		hs.add("kEC7OlpPnZRxCUyVwq7hig");
		hs.add("W_bEI5C6A2Krw6JTEtZn_w");
		hs.add("ZMbvNZ8CXNmVuStXgx6U0Q");
		hs.add("ghnQrKVEjiWZ3UE1XDzJUQ");
		hs.add("66jI6z-JuLasvd692ymycg");
		hs.add("N0uN3AZQyCPbxUDMyPaldA");
		hs.add("Je396Ev-dvAvl3ei-O0EIg");
		hs.add("GELMS90-RDnSuLEFPxnt3w");
		hs.add("ateowLnq6kpgNNWHzCDByQ");
		hs.add("DRRxajtJ_jUbF4YNJxp-0A");
		hs.add("MKyk4F4HSzHF8v-4cYe3Ww");
		hs.add("s74Tq6WKV1b91UFRr7ch7g");
		hs.add("wan0X-oHpLgGTPXqaICZCw");
		hs.add("tQpYnf3P3Q_OQLYYJvlV-A");
		hs.add("vSZDiKiF8vf9zt_BcDL7GQ");
		hs.add("g-Q7G5Q2zHb1BqoF8pq-OA");
		hs.add("76lSMjkrbLxTWeylGZvjhw");
		hs.add("_wZTYYL7cutanzAnJUTGMA");
		hs.add("6X7vAFv-Xj1TPcrJK7H2Eg");
		hs.add("apCfJVnRyaw6oVUBKujpUQ");
		hs.add("VC0VbRhQqvXpolK3pFuZPw");
		hs.add("7srDFwPPnzBaQoPW55Dc8Q");
		hs.add("RIeWXLMHZQlYprYt1x2f1w");
		hs.add("E-_PkZNDuYxW1zs4XFlVmw");
		hs.add("wZwZcte4lcbu51NOzCjWbQ");
		hs.add("HjM7hG2Fqrn6ZGmffs5aDQ");
		hs.add("b7DYG6rI5l-9oHxBJ0iNtA");
		hs.add("BJfjd8oEMW_zq8KTkixyig");
		hs.add("HmNMIuTR3lH0OTpkog2dTQ");
		hs.add("7eYbf4F9hNq6BQhUnLrWZw");
		hs.add("c3QcUPlgX_3O9Airt2893Q");
		hs.add("cfNLfmsM7w-3oVEnmcvHuw");
		hs.add("96rDpZ2OBW293QNWPIPV7g");
		hs.add("KJnVuzpveyDrHARVNZaYVg");
		hs.add("5-rL_08xlI2i-xsswFyYqQ");
		hs.add("6fpd8iXiUypI7eVx-hJhMA");
		hs.add("uuz1Um4FzxNxqBMgffSPJw");
		hs.add("Zww-ckcRf0fvu_yKGFZvPw");
		hs.add("zCWxbKIX6vFlPIqlZso0Mg");
		hs.add("yT3OITYWbjqKM15mGNXmyw");
		hs.add("YKVNzbuGpgszyG5OuFHU3Q");
		hs.add("vcTQNi3qj2tSWOe6Fv2XsA");
		hs.add("3WYYCZq4spbRviIFN7dkJw");
		hs.add("oPsn2zSMchH0I4AuiiH5Qw");
		hs.add("8XHad9b3D7Zynt5ZkrQK7w");
		hs.add("vfzUNcV9B3RhDyuZp0I1pQ");
		hs.add("mqQwChPNN4o4DhAzaGntIA");
		hs.add("D91dby6NHj13Cp7cDIj4TQ");
		hs.add("fjAQGf-iJlVjD2vizzuORQ");
		hs.add("9SKdOoDHcFoxK5ZtsgHJoA");
		hs.add("8Hn5X1AqgmSLHRG2KgBJBg");
		hs.add("VBhgkRUNe9gjc1HpmHA3Zw");
		hs.add("_F2DNPjsqgkAd50zuX8dYQ");
		hs.add("GoS_IBdFdjZrQ7J2LSrCMA");
		hs.add("1bnte8O-rO_RcRlp9y2u7Q");
		hs.add("4TSly_fRMGkGsFV9rsfjdA");
		hs.add("G0nUhYF2q4tnoOPwCjXLig");
		hs.add("X4CnrlflZBDMRzSPWfMBaQ");
		hs.add("VcgYPX95J6_mfrEopzR0Zw");
		hs.add("IwKHe7mwjF6uIwfr44ERlw");
		hs.add("WeibALgHYelRsdOQ2Dr2Lw");
		hs.add("6sqAj_mXmYkZ3UKsyRGGHQ");
		hs.add("zMN8UGd1zDEreT58OCdnyg");
		hs.add("s5ZdjjFX3CS2uS6_oVH7CQ");
		hs.add("WuFqL5uURZwfootmgAMCyA");
		hs.add("7xbTnoyaai4JTkZ8rFPQTA");
		hs.add("FHqwLwpLjUjeLP-IdG_o_w");
		hs.add("zmFc8M-hS4uuyY0hklIpoQ");
		hs.add("Edj0quZE5k1WcAtf883j6w");
		hs.add("KvZ-05xTCXzEx98ZHsZ_Dw");
		hs.add("U87W6T9vjwWnp28Zjnn4pQ");
		hs.add("s6DB2eqwmzV6sz_dNMyZBg");
		hs.add("7u55OIKwMmnWGnobEEUNvg");
		hs.add("FqzgT9Y-Yu7jiWdHnGW-kQ");
		hs.add("VdpO2eJQy3zRxySElLXsMw");
		hs.add("BD74uSwDe175zEqfppDRvg");
		hs.add("ejS_lQteyzG6PR4gxZN-FQ");
		hs.add("iJe2cL7QEKOn5GxK76-HhQ");
		hs.add("qmIT3LC-kMNiOy7_XpWNUA");
		hs.add("UrS9awRtye1YFlW5V1bWzw");
		hs.add("yGmdo1ENajB98iryHGoWFw");
		hs.add("3uGQDrswQnDTns4ov0Ae3A");
		hs.add("sDozh6iTylTJD26d7xcgGw");
		hs.add("Hd6Kh_BcorPhCWVn6pMu4Q");
		hs.add("CnSDnel9GZ6mRy73zWBKiA");
		hs.add("ravINrZil-a_nAl95-KjDQ");
		hs.add("An1vrRPlSZ1tDFsAuNqSmw");
		hs.add("7_7fxuG9ESAFmx-AiMsJHg");
		hs.add("woJbuuWU7zyXA63YV3p0gg");
		hs.add("yJDSMugu_Pom3pJE8MRrJA");
		hs.add("TfTlOE6h9E9o34dEkw9L_w");
		hs.add("zgyAbIVPD5Vjcsn4EkKLKg");
		hs.add("A3xyx-Y_-t3TwBD9E--Zzw");
		hs.add("iYFAQAF_Y2XCHuXL_Dgg3w");
		hs.add("Pq91OM8RI_Rcr6PpXQajsw");
		hs.add("eRRyfI6QVvSviirRF8UGzQ");
		hs.add("tvmKrU0qwXI7mV6XnefRYg");
		hs.add("VMcImxyIFZ35Chetz1blPg");
		hs.add("s5SR0faaaE8PmiZjeIJv1Q");
		hs.add("VczlsEmHHmFACnVnA2_jQA");
		hs.add("8SBXsNM4KCyN90r_bNFw2g");
		hs.add("EcCzmA_FJDGRgRfhjCOMBQ");
		hs.add("x02bWSJbx3VLZg6QytDpxQ");
		hs.add("lytsOcdjCk9KTf20eHbBFQ");
		hs.add("2b3PJCEQLmioiAhoMXs2hw");
		hs.add("js34oCYYc3od-WQcR1_yPg");
		hs.add("kqmOzL836sk2GK9eObwi4A");
		hs.add("FMzJJjpd4Pd311StIKkVKA");
		hs.add("EMD6yobRZBdHc6xeXRj4aA");
		hs.add("etYqrJTCE2_yMxhqdnGd0A");
		hs.add("R6zar3Qi9tEk2guELwKALQ");
		hs.add("8x9Mzb7gX6SEHQIlSDpU8w");
		hs.add("nilhvDCyVBuv7gnNkPWZQg");
		hs.add("xY1sPHTA2RGVFlh5tZhs9g");
		hs.add("njd_x0C4UlO7HWvsOmg8yw");
		hs.add("c6EpEvtu-h4NbCGt4Q-S8g");
		hs.add("WjLtEWGvPSIfwMZXUMHX8g");
		hs.add("G6mZKMiDqHDgH92IOg9QhQ");
		hs.add("k8Vih-WEeO5Jmilhbm2xmg");
		hs.add("74qDPs2dR6gSzDp6N1U-Og");
		hs.add("zSzE4rW9FE3fGqiEzZ91Vw");
		hs.add("8N4lH3Lo9do71hVgajdOcQ");
		hs.add("7ITniQpQnpzm47FzN6V4EA");
		hs.add("uQn0lwRKxlqG0UFZYlc9ng");
		hs.add("nhToFLPoqNixNbRK4-xFQg");
		hs.add("Hs-EOmxbjrTUQgptmphHRA");
		hs.add("1XXGV_HvIHLC2C1mJUFv0Q");
		hs.add("mzotSaJNpWydcoVX7sr4qw");
		hs.add("JAGAwjSDoDIxaPq3cyTfWw");
		hs.add("PN3aQAH-RONnK-ahkNm0xg");
		hs.add("uov-UZBQLxzyIL15anzRww");
		hs.add("qQkEmvb5uKcPFPGxx5WQqQ");
		hs.add("O-FX-jCyevCbUmD45M8FWg");
		hs.add("wNsmt1hF1uv3YvbwXZMAoQ");
		hs.add("CEswyP-9SsXRNLR9fFGKKw");
		hs.add("EwHIy2ciDTtmlj7lpa9dng");
		hs.add("XoitWJUjHcdBl9GqHTsdjw");
		hs.add("5PSjlaVzR1RooMhYmjRmBQ");
		hs.add("RzVwAdOxT9JQkeoeBMYPoQ");
		hs.add("00ITZP9lfLKPRiCaRnzAtg");
		hs.add("z9H1at5bT5FKfPUR6LPo5Q");
		hs.add("JkV8OwKCqzghteyspyZqZQ");
		hs.add("rO3saNBRU2Pg16RyfEP6-g");
		hs.add("yaB7JCmLb6Ka5Jpdo0GGlw");
		hs.add("DN4kjoM0K31HR230i3n7WA");
		hs.add("uq_cgrcgLzDN6NbVWXHHgw");
		hs.add("lblNkTnCgCTja1Y85M75xw");
		hs.add("gfE3L51Hdd929VXm1zEexw");
		hs.add("4eqw9xCbCmNQPV-AQJcXPg");
		hs.add("7lDNKKxMV84KIS1OVZOepw");
		hs.add("ePP0Eqz8JKSbtdt2phiB4A");
		hs.add("XeFNQqz5vVsVIcTjNuXcTw");
		hs.add("r-pBY6vR_Iu5XhPRvPnquw");
		hs.add("jd7yAsF-T4OlI4ejkJYJrQ");
		hs.add("JwjDSrMrKmHUXYqoIvTgUA");
		hs.add("ntJAKLAq0cXzzdFgPoo0Iw");
		hs.add("tC_T3DykMOlLV4p7iiRDWw");
		hs.add("3N__CAwM5VZOhRKmxMtImw");
		hs.add("I4uAbB_i9dLtPkWJvyOXiQ");
		hs.add("2BSF6wu1V3KfyFJf1DQ3DQ");
		hs.add("uS2T2BMt7_EE7mhM3m3I7w");
		hs.add("GPAg6fpHEiYNDbd_QWTc8g");
		hs.add("9cAWufXd7SvykcNHutxFug");
		hs.add("814EMcyabpse8-Kmgitg7A");
		hs.add("TKE1cyjs9q2PoqMXqEV9Eg");
		hs.add("tGx7BSyqWDeppMvt2aQw_A");
		hs.add("-1lvWTeV_RI1weq8FTnPRw");
		hs.add("Okg-KUAwf3qJ4kkqkAn6oQ");
		hs.add("u6ZeJSqTxoQeQF013RtkNw");
		hs.add("yTz8_GylkgCkuiBjSz8mIQ");
		hs.add("61sn3yXmTPEqSt7-KNDPmQ");
		hs.add("vAnxS2AeDy2L1wTK84PAAg");
		hs.add("m79L5WLftprDSKdXEtdrIg");
		hs.add("N9Fhc21FV5AokjZm54TNYg");
		hs.add("scr5gHaPC_36GtaCxmJEHA");
		hs.add("ECBzFJhjbTyPHG7hZHPh_w");
		hs.add("4sDNVEpeCKsatT-H_or1Vw");
		hs.add("3g2ofV7mhEoPyfF7vFMObA");
		hs.add("cjjZt2oOkk0F152RkQMfQw");
		hs.add("jz4kvnNmFL7_coXYl6NAWg");
		hs.add("onwUqByAIhtkyJsEITV5lQ");
		hs.add("4AKcmN--0hbF0kX9pg8scg");
		hs.add("XGBK1_iyfPC2_0nmAo12WQ");
		hs.add("OUpcKYGbVYgSS1Oo7aQ56Q");
		hs.add("KFyB0ueHjAfN4oadjKsTEw");
		hs.add("WT-v-DgQvW38DewVyTLdTA");
		hs.add("1ZzAk-yucZfq_Msv4-lHUw");
		hs.add("QpDqCDp0L3c7U36We4_duw");
		hs.add("DUADdTz_2yQvgQ701IhL0A");
		hs.add("bibDVZAHz4Q9TLn1iRwlbA");
		hs.add("Q4ULAiIE2qCA4RYplCTrUQ");
		hs.add("Cq4prPqm0KFrCf_wI8Pufw");
		hs.add("0NNw9CHm0X8LJBvmIJvBIA");
		hs.add("lddbHJKgFvnVWabK-M8TPA");
		hs.add("4MwbNHAVZ6aRE1FWks-HRQ");
		hs.add("NGJDjdiDJHmN2xxU7KauuA");
		hs.add("eZT3KnWP7Zz93KH0EvWSlw");
		hs.add("8oqcpmXrymQ1RRMK12S7QA");
		hs.add("sMO71vGV8wkKujOle3-v7g");
		hs.add("FbSfo_4DUCPiOpRTzlssJA");
		hs.add("kAXwEMkpcKMObw45QJGqnw");
		hs.add("E3RjJH45EX6rHYDs0TYSRA");
		hs.add("ilJiRYZgxjrEu2iexKu-pQ");
		hs.add("UDChQLVuz9SYgyyIoEqDkQ");
		hs.add("GbI7f5CJtv5FtOnZ3yOasA");
		hs.add("pQ3kRVmttsV1bHxuTf7TAg");
		hs.add("k-D2NUfaUbuQzPaMXniXcA");
		hs.add("ccRPyxvCzkhwpb5ClCbTsw");
		hs.add("3cKrdTUKV6lNDcckcHcCvg");
		hs.add("59VVVF8Y9UD1tEpXD5PghQ");
		hs.add("ar90fbRbQtiyZLtwjwwXUg");
		hs.add("iTBQsH-YU2RwrCP_Gaudeg");
		hs.add("ZQPnmwLikPeGD0_1CVqd6A");
		hs.add("jeLsCAGadupSoIZaAR23QA");
		hs.add("SWSZdo4sBhrcQSmN5e1myg");
		hs.add("uJYw4p59AKh8c8h5yWMdOw");
		hs.add("57YV3wsiNBp-aK25qjUeww");
		hs.add("dBnd-XxU5FUZ_gY6fkiJxg");
		hs.add("1cryKcsY47JGigLuUeMsTw");
		hs.add("DEg-YquqSx_-Klk_cyafDA");
		hs.add("wOvAbdVYDaguotpdSALsfg");
		hs.add("pe6OU0r4NqVl6qfurqXInQ");
		hs.add("0vC19KuagYe9RUXKDP13_Q");
		hs.add("6Tdz7MvJA5eLBAWOV3fW_A");
		hs.add("DZUuB-afy0GEzlPdDHvuFg");
		hs.add("NSGrSt6KZn8gDtqw_Vh1mA");
		hs.add("3uNDF5JOSAzBAOStQd1pIw");
		hs.add("SJzjyB_qD2CjQPVU7qSsbQ");
		hs.add("aRVcgle3zySWGXQ8tWmrPQ");
		hs.add("QYwnYMzjXESzEjc-yAHC1A");
		hs.add("brmD0tup9CaPN8h3fm8x9A");
		hs.add("tdcjXyFLMKAsvRhURNOkCg");
		hs.add("14K90G-hbfk795NY7cKxMA");
		hs.add("K9rlhLtpGjpzcVqZ3qxmug");
		hs.add("Bc-whgNf9N1VdcxAqfpjGA");
		hs.add("uvdS1a6h0wS0R9gryFX4oQ");
		hs.add("DK-SRzWGFPykx4pIvsF6_A");
		hs.add("k6PuJ964NF2NEoXoOg0ijA");
		hs.add("BAFb16CUpRBKjG0a9189GQ");
		hs.add("BBfTiaMxtNOSa_sthMy9Pg");
		hs.add("Jk6PigLJDvD5LYsh9h-i4w");
		hs.add("n3kfs4IMPijyhiNg7S0Bzg");
		hs.add("B_1LLEKSddI0hvOuB6S6VQ");
		hs.add("h869Y00XkD9oeL60n5-8xg");
		hs.add("vT12uXtdBQ10_lUcl-M40w");
		hs.add("OdD1GuGNQ64ssJmMJ_D9RQ");
		hs.add("hZRLGfRrZTo9up2P-0aAHg");
		hs.add("R4catpIG7txsNMv1ZBL5vA");
		hs.add("nc1FeztHnMIN1C-NShjeGQ");
		hs.add("HRJXrlHvba77mu4Yyi0QQA");
		hs.add("eQcX-d2ZveSTOE75BipOXQ");
		hs.add("TCoTqRkuZEAiWq1KYCczoQ");
		hs.add("kPy-9EH9on8P4VA98GA_9A");
		hs.add("B4OGro6mt9WBqCDowsMung");
		hs.add("ImJ7QAw6T6ayJT1AGr7OgA");
		hs.add("MC8Fv4Hd4reUsTKJYoZPfg");
		hs.add("T6hYDhIZAzPW98_OEbqOSw");
		hs.add("TrUPQ6CgVw4CpUuIk-AE2A");
		hs.add("9s8J5SQaZYXzDnAmgXCQBQ");
		hs.add("zzK7j06Pg8YWkQHzgsTuQA");
		hs.add("mPnKGfoCvAd7N7Q58EBRrQ");
		hs.add("EolW2H_wkpYwWbBURN_4gQ");
		hs.add("wHyEHBSjRtYPhPpIR7W_1Q");
		hs.add("E3n771Z4Uqy46WNaFS5u0g");
		hs.add("OMxNuGJsC0HlooL58tZDJA");
		hs.add("Fy94rZs9B_XS6YRCRjYIjA");
		hs.add("PWG28q4JFOc8FiRBjnfCkA");
		hs.add("uqxw_geNvNbPs_YY4TAhCA");
		hs.add("4mNRylz5SZZ-dhJOLmfkBg");
		hs.add("G1LaLNJObuAwZGAcJ7OY0Q");
		hs.add("PmGgA12IFDwedPDAjesx3Q");
		hs.add("HrSowDDXw71VD_d-4g7I5g");
		hs.add("I7RzNCWg_uVzUJhm9lrB4g");
		hs.add("NzDd3ubqU4j2-5UB8hZdjw");
		hs.add("t-cM-sIkmJKO_9RZDARusA");
		hs.add("jS3cHd1E5TuUZbQWpBZqVg");
		hs.add("IW-NYIHk50mXV5Nz7nSGyw");
		hs.add("RhEsncyHehxN_F_CBdpLzg");
		hs.add("IUnRnZHmA56Tgr2acpHRow");
		hs.add("dt2JuMHepQgj07CtYqRLeg");
		hs.add("NeUf9FyCCIN4MEseNyqkXQ");
		hs.add("jJfTh2O3M2Q716akd9Dr9w");
		hs.add("-6JY1T0w4XETux5kGOj84g");
		hs.add("J7XRfg3ScS5K7UyM5Te-ng");
		hs.add("2-M1_ok4NZ-fSF6SbBsp1A");
		hs.add("BP97hODPAzQvspa3NcyZPw");
		hs.add("pPWre8lbVAssER6CN0uWMw");
		hs.add("Cp6JGY5YIRncTV_My9nf9g");
		hs.add("FQudBiBiz9bGQLF_kK8UCg");
		hs.add("lf42gtgq_2_jPvjfp_K1nQ");
		hs.add("SgGINtDKQgoXoAnQgrDKDg");
		hs.add("Cp5_NSJFNgylD5SUdmT8nQ");
		hs.add("ZXlO9S1MG2I-L5uLSF-nPA");
		hs.add("Mmz8iWNfeXkp1dIP0FkTaw");
		hs.add("IFx7uG8_uAN1cJqMB9wyFw");
		hs.add("4UVhuOLaMm2-34SrW8y-ag");
		hs.add("_9BqmRowpWfy4wDPXLSDHA");
		hs.add("Oi8IOoJOEX9JZYK65fUrrA");
		hs.add("5IbZ0LjSydLAfB9NOyYOIQ");
		hs.add("ioXu3MhPt_v8f5wTWJX4ag");
		hs.add("7ceEkl2p0eqehcASjYeL8A");
		hs.add("OdNwrZgfPp2Xkj8lEPMJeg");
		hs.add("gsIv6gvuAFlZ8CIA16vgUg");
		hs.add("5-zorZMowhrM6fEMOCAGqg");
		hs.add("ufOY2lQHDgSvou3YLT8gHA");
		hs.add("UB_JlcIRgQsdKzQZQyHjuw");
		hs.add("VF9wvcgVPDVa9LBDHPrXuw");
		hs.add("rLv5DPLnO67TCHIbbBWYPA");
		hs.add("PotMToXYlxZRF2_9TheRxA");
		hs.add("FGePlnlKXHxBrxYMNGtdAw");
		hs.add("2ceeU8e3nZjaPfGmLwh4kg");
		hs.add("GY56AE5HGV2dWcRNGXumbQ");
		hs.add("waW8k-4ebmByGUJtndmnJQ");
		hs.add("XYpzV6VWQpq6fP0Dmu4PhA");
		hs.add("f8wqyzyqUbiWtWyMgkxbuw");
		hs.add("rWmutW2jsCkMzyWjLdZUjg");
		hs.add("VVeogjZya58oiTxK7qUjAQ");
		hs.add("u3330_sZNrfUbPGe22OypA");
		hs.add("eWPFXL1Bmu1ImtIa2Rqliw");
		hs.add("zrsG6jJRUnOsU9wv0zS8iQ");
		hs.add("0_LZEAYsexEZS-OFTjdjNQ");
		hs.add("uqisw8IXD5ZutU4MT2MQVw");
		hs.add("G90_hrydwP7mZEbehciP7g");
		hs.add("nofTfb0JTYASuOeQCuLfrg");
		hs.add("m6N_2Slp1QLZc4aM8SF2xQ");
		hs.add("eltBRxiy9QlXA8QwgoyZgA");
		hs.add("y_jsnI8NUThDecWmgL_soA");
		hs.add("c0iszTWZwYtO3TgBx0Z0fQ");
		hs.add("6H2c3qMbO5vAJmiTBRXI4Q");
		hs.add("qf3yb-SxTe0rbrZ98tdw5A");
		hs.add("vz2zQQSjy-NnnKLZzjjoxA");
		hs.add("lzl3cfgVEGMtezF8oRqXDA");
		hs.add("upEYCgGGZOuTvwzqnKZK5g");
		hs.add("G9DhtHJRTe2i2hxyf4ev_Q");
		hs.add("4CsZK1YOP8lCLH9ZSf0LMA");
		hs.add("ERtc-EXdP9erEBoh7droww");
		hs.add("FDfK4HygC_P-Idoy_K8PKQ");
		hs.add("gUt-pPUpOVVhaCFC8-E4yQ");
		hs.add("MV-i4L90OgXO5fFIfT4hQA");
		hs.add("Oc-F6O91vOe3T8iOsCBB8Q");
		hs.add("AhoyhGxkDkejYRcI_uql8w");
		hs.add("kSWu7MCwCTjqsmRzrnx92A");
		hs.add("IfOO5jX0C0n30UMISOYgSQ");
		hs.add("twzgrzphXT7oa0II673-6A");
		hs.add("8PJSfnXpHoENxD-rsGGXWA");
		hs.add("MegAhl7ZS2s2J1DT7mNXxw");
		hs.add("0tUlPATGNNR7zq5uzh3nog");
		hs.add("6RVoRilHow-zehz_qVZQCA");
		hs.add("h16e3XoDeeNdWjOT7JtRnw");
		hs.add("_rrWTz0W1K_eWafh-8r3fA");
		hs.add("RqbSeoeqXTwts5pfhw7nJg");
		hs.add("8LmoxL6HvQodk0l5PPgaFw");
		hs.add("hOf5nmeNTOkQ_Oe2gQoEkA");
		hs.add("LzMEkj7wm7kj8jkpBkxWNw");
		hs.add("p1huyy7MxRPTWqFq0FGJGQ");
		hs.add("pU8beAibeYjH5-KTsJqVYg");
		hs.add("b0Z17Dslw8bT-8qPR2m6fg");
		hs.add("uU70AmVxV_OOgkumhUpu-g");
		hs.add("vSf0pqvaLp5sVSjJPeOqqQ");
		hs.add("PSJYQSzCX8_GJTStU-P8CQ");
		hs.add("jawQZtL6i6wNYcD9pftGEg");
		hs.add("mmET_2OZTfcI1VDJRMpEkA");
		hs.add("mDtHcmIXbtv7J9N4HSsgcg");
		hs.add("liJ7u970FYGtRTo5EOxvqg");
		hs.add("EoVGIsaatkdbWLY9qyFcgA");
		hs.add("ZEpSYuDb9BgYD-XF1mc_jg");
		hs.add("HrgYs4zFklk7KKxm4CQUkA");
		hs.add("KDQqjVfqmLDwddpt3yKVNQ");
		hs.add("sLTur8Xo0ZAWx5Q3QMTw5w");
		hs.add("0CeEgarUoVP2Nq9s1Mn0Aw");
		hs.add("7JZ29DY1lQ0DZVu5zHEleQ");
		hs.add("Fe2hv9MM9E6mmcfJgtylgA");
		hs.add("LVngid2NNh2s5cAjuOw6tw");
		hs.add("PQt8GULqftvPaAhu0ribTw");
		hs.add("OSsueRKTxM0MEbgIRsUebA");
		hs.add("USPVxT1jYvarxC8lZJeLMA");
		hs.add("2decJ0oLr_LI1TI2Po5GlA");
		hs.add("U3FZfxY-g6SgQf5ZT6oU0Q");
		hs.add("VO-OXdvcTHnhKhkNjjJDeQ");
		hs.add("ugnkhOtu4bZziV9JJYWN0w");
		hs.add("hAgtic2abji61215w8_OVw");
		hs.add("GGyHZtnAA5LBgouB-32ARA");
		hs.add("xVNehV47VEyx-Uj0DTdPEw");
		hs.add("qQw1b6f6eLu3pmVDLw3e3Q");
		hs.add("r1YB-iVpNM8oP2eEqyaVbg");
		hs.add("rgmptwPbBH1wLpiBHcbIhA");
		hs.add("6SxAOEXHzNjWQMQ9Nnos3A");
		hs.add("MVH3JOKpQvMTP4jxwBUhkA");
		hs.add("AB5RgQ0ZnMThdqgFS3cPuw");
		hs.add("IgaruuknYwCr9afeDYQ_yw");
		hs.add("JZJqJadk9pSoCGT7VTwBvg");
		hs.add("7UTlEVHU5v2xBLdkGghyzQ");
		hs.add("nBfusVbqwul0BU0Rcrlelw");
		hs.add("IVcJFeRGNWpn4sZv-mWpiA");
		hs.add("CTOz7KhvX2QNvBXBXOvV7w");
		hs.add("eeVoOZoa7huk09dfYga0eg");
		hs.add("mU-6t2BvgkE9HjlYgE-3zg");
		hs.add("at3I3txb7I7TE7Qvl3yIZA");
		return hs;
	}

	private HashSet<String> getGoodBarFood() {
		HashSet<String> hs = new HashSet<String>();
		hs.add("UsFtqoBl7naz8AVUBZMjQQ");
		hs.add("5Udv4CASAXB2eH66TefWPQ");
		hs.add("vSZDiKiF8vf9zt_BcDL7GQ");
		hs.add("KHOHjA8HOcTlFBCtMQFv8A");
		hs.add("qIhBNeE64skjowRs6TTwJA");
		hs.add("CqhsIZ7TzCfJTrZqg5-gqQ");
		hs.add("qz4ZOcv-840UjfCEYI4qZg");
		hs.add("d7V3ykQHqChv0KtXEanKLw");
		hs.add("xuEsUDFIWIEnBXvj1EBXlw");
		hs.add("DQlVVaGbMxf3Ed6rp8A3kA");
		hs.add("ht17atGW3tP8dFeiJkXI_g");
		hs.add("Btmq4WdwevpVWTPjhzf1YQ");
		hs.add("sC58XGwsZowovN1CnKktOg");
		hs.add("KdSJITuZhQmuQv5NyXpHcg");
		hs.add("CLW4LJCYbAkwlgNWB2rVbQ");
		hs.add("-gefwOTDqW9HWGDvWBPSMQ");
		hs.add("lPAHpSIc2MvY06bWxrFRiw");
		hs.add("2ceeU8e3nZjaPfGmLwh4kg");
		hs.add("aS3B7B2CgaJMJ4kJ2RtxBw");
		hs.add("OaiGAZoW7TQyHfKJAgu5ZQ");
		hs.add("JuaQPvvWdbJ1B1Tn0jIt1w");
		hs.add("qsBet6HtxE0x41cUYl8vgQ");
		hs.add("E7nk0lC317pGxMX56gvaVQ");
		hs.add("WhBxWYRj6rycigYqdXY9cA");
		hs.add("FHqwLwpLjUjeLP-IdG_o_w");
		hs.add("iXA8Y2bzvZo8MjALfZxrIg");
		hs.add("zsCxklQ4G2WK1xS7GULu3g");
		hs.add("G90_hrydwP7mZEbehciP7g");
		hs.add("U-0hMfagGtjYZCYB1i0WNw");
		hs.add("o9nCXNC14VScabiy2bftgw");
		hs.add("ejS_lQteyzG6PR4gxZN-FQ");
		hs.add("VC24HxKvTi_2ZVWiC3j1MQ");
		hs.add("H52LFxw13LBS6_ewxCwlfg");
		hs.add("uyg5_fHXJe837GXd-4yiSQ");
		hs.add("E_TSzYjABEzD6DXsvjZnsg");
		hs.add("iPIbM34qhj3Slz1HiWVYVg");
		hs.add("5tey93wPQOb7z6jOLJZ30w");
		hs.add("6FFLrPh0z_U6JpIUANuaYw");
		hs.add("CLZwf-pAbUXRKiWhnPo2Qg");
		hs.add("Gq092IH6eZqhAXwtXcwc6A");
		hs.add("lV-Kh0fLS3KgBrpzPhC2oQ");
		hs.add("dBnd-XxU5FUZ_gY6fkiJxg");
		hs.add("7PQRP9l2cSSqjbQdsXL8yw");
		hs.add("pLdz4dZ6fUxp2GgBRNPq2Q");
		hs.add("MXOdsPTLQPsQK9hUq01DWg");
		hs.add("xsSnuGCCJD4OgWnOZ0zB4A");
		hs.add("6uZqR0MsU9UMEX_FftYSdA");
		hs.add("Ko08oUwSm8E8IxSrunx7rA");
		hs.add("vSf0pqvaLp5sVSjJPeOqqQ");
		hs.add("7ITniQpQnpzm47FzN6V4EA");
		hs.add("tf5qrrarVIVYOy0evKrayA");
		hs.add("NHy-HT-FI305jqgyeIWPCQ");
		hs.add("HrSowDDXw71VD_d-4g7I5g");
		hs.add("dWkk-jlHMcMdLgcIFl_KvA");
		hs.add("IW-NYIHk50mXV5Nz7nSGyw");
		hs.add("gYN9Wp2yivX6gNhgg2l8_Q");
		hs.add("_z0oAuTO0Jk07sMdoPE8gg");
		return hs;
	}

	public double getRMSE() {
		return Double.NaN;
	}

	public double getMAE() {
		return Double.NaN;
	}

	public double getPrecision() {
		return precision;
	}

	public double getRecall() {
		return recall;
	}

	public double getTrainingTime() {
		return trainingTime / 1000.0;
	}

	public double getRecommendationTime() {
		if (recommendationCount == 0)
			return 0;
		return recommendationTime / (double) recommendationCount;
	}
}